// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace NguyenThiLuong118.Migrations
{
    [DbContext(typeof(NguyenThiLuong118DbContext))]
    [Migration("20211215062829_Create_Table_NTL1118")]
    partial class Create_Table_NTL1118
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("NguyenThiLuong118.Models.NTL1118", b =>
                {
                    b.Property<string>("NTLId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NTLGender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NTLName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("NTLId");

                    b.ToTable("NTL1118s");
                });

            modelBuilder.Entity("NguyenThiLuong118.Models.UniversityNTL118", b =>
                {
                    b.Property<string>("UniversityId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UniversityName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UniversityId");

                    b.ToTable("UniversityNTL118s");
                });
#pragma warning restore 612, 618
        }
    }
}
